# Generated by Django 3.0.5 on 2020-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmany', '0003_auto_20200430_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.URLField(),
        ),
    ]
